### ISSUE TITLE
soma.web missing after install

### ISSUE THREAD

**Issue by BastienCagna** [brainvisa/snapcheck#1]
**Describe the bug**
I tried to create a new database after executing the 3 installation lines in my virtual env in casa (cati_platform).

```shell
$ python -m snapcheck /tmp/test_snapcheck create
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/network/lustre/iss02/cati/dev/cagna/projets/cati-tracto/venv/lib/python3.10/site-packages/snapcheck/__init__.py", line 3, in <module>
    from soma.web import WebBackend, json_exception, pyqtSlot
ModuleNotFoundError: No module named 'soma.web'
```

**Environment:**
 - Engine: Singularity
 - cati_platform-master-5.3

**Comment by sapetnioc** [comment]
This could be due to a wrong Capsul version. Did you install the 3.0 branch ?
